# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'D-HelpConsultant' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 4.5.1'
  pod 'SwiftyJSON', '~> 3.1.4'
  pod ‘AlamofireImage’


 

end
